### ISSUE TITLE
Como aprender (protótipos de tela)???

### ISSUE THREAD

**Issue by leonardo-minora** [tolibras/ideias#13]
## User story

Como aluno gostaria de estudar LIBRAS para satisfazer alguma necessidade comunicativa que tenho.

## como fazer

- html + css
- arquivo : prototipo-ui/aluno-estudar.html

**Comment by Caca404** [comment]
Link: https://www.figma.com/file/rb6RyREsNCwTlp9PGBmjqN/Como-aprender?node-id=33%3A2
