### ISSUE TITLE
Como eu reviso (protótipos de tela)??

### ISSUE THREAD

**Issue by leonardo-minora** [tolibras/ideias#14]
## User story

Como aluno gostaria de revisar o que eu já estudei anteriormente para que o conteúdo fique na minha cabeça.

## como fazer

- html + css
- arquivo : prototipo-ui/aluno-revisar.html

**Comment by arthurmelo777** [comment]
Protótipo da tela de revisão finalizado.
Link: https://www.figma.com/file/culakulEuNjnghziSioh3U/Untitled?node-id=0%3A1
