### ISSUE TITLE
Adaptar código HTML CSS JS com o Bulma

### ISSUE THREAD

**Issue by leonardo-minora** [tolibras/ideias#32]
Tarefas
- [x] Instalação CSS/JS

**Comment by Caca404** [comment]
Como o framework do Semantic-UI é muito quebrado para continuar usando, e com uma pesquisada melhor nos frameworks interessantes, é melhor adaptar o site para o Bulma.

**Comment by Caca404** [comment]
O Javascript puro já serve, não precisamos utilizar do framework
