### ISSUE TITLE
Revisão do formulário para definir problema do usuário.

### ISSUE THREAD

**Issue by leonardo-minora** [tolibras/ideias#9]

**Comment by leonardo-minora** [comment]
link para o formulário https://forms.gle/kGvmGDWGhW9kswNk7

**Comment by leonardo-minora** [comment]
# Perguntas que eu colocaria

1. Você já aprendeu algum idioma na internet? (Sim | Não)
   1. Se SIM
      1. Qual(is) site(s)? (aberto para digitar)
      1. Quais recursos você gostou de usar nesse aprendizado? (aberto para digitar)
   1. Se NÃO
      1. Usaria um site para o aprendizado de língua gratuito? (aberto para digitar)
      1. Como você acha interessante aprender uma nova língua via internet? (aberto para digitar)

**Comment by Caca404** [comment]
link do formulário para user story https://forms.gle/UzfozrFrBKy4U3XV7

**Comment by leonardo-minora** [comment]
Considerações:

1. Identificação deve ser opcional. Nem todos querem se identificar num formulário de avaliação.
2. Também acho que o termo __Gamefication__ pode ser retirado da pergunta. Pode colocar algo do tipo, "Você conhece o termo Gamefication?". As pessoas estão querendo aprender Libras e para isso não necessariamente precisam saber o que significa o termo.
3. O formulário é para definir o problema do usuário? Se sim, o formulário tentar:
    1. Saber se a pessoa quer aprender Libras.
    2. Por que não procurou outro aplicativo / Site?
    3. Se procurou, por que não continuou aprendendo lá?
    4. O que gostou ou gostaria de usar para aprender libras.

Se o formulário for para __user stories__, como citado, vamos abrir uma nova issue com esses comentários.
